spring:
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate.ddl-auto: none
    ddl-auto=none: none
  h2:
    console.enabled: true
#springdoc:
#  api-docs:
#    path=: /api-docs